# Data Quality Audit

In [55]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

prices_22 = pd.read_csv('data/raw/precios-eess-2022.csv')
prices_23 = pd.read_csv('data/raw/precios-eess-2023.csv')
prices_24 = pd.read_csv('data/raw/precios-eess-2024.csv')
prices_25 = pd.read_csv('data/raw/precios-eess-2025-.csv')

In [56]:
prices_dict = {
    '2022': prices_22,
    '2023': prices_23,
    '2024': prices_24,
    '2025': prices_25
}

### Column names

In [57]:
for year, df in prices_dict.items():
    print(year)
    print(list(df.columns))

2022
['anio', 'mes', 'operador', 'nro_inscripcion', 'bandera', 'fecha_de_baja', 'cuit', 'tipo_negocio', 'direccion', 'localidad', 'provincia', 'producto', 'canal_de_comercializacion', 'precio_sin_impuestos', 'precio_con_impuestos', 'volumen', 'precio_surtidor', 'no_novimientos', 'exentos']
2023
['anio', 'mes', 'operador', 'nro_inscripcion', 'bandera', 'fecha_de_baja', 'cuit', 'tipo_negocio', 'direccion', 'localidad', 'provincia', 'producto', 'canal_de_comercializacion', 'precio_sin_impuestos', 'precio_con_impuestos', 'volumen', 'precio_surtidor', 'no_novimientos', 'exentos']
2024
['anio', 'mes', 'operador', 'nro_inscripcion', 'bandera', 'fecha_de_baja', 'cuit', 'tipo_negocio', 'direccion', 'localidad', 'provincia', 'producto', 'canal_de_comercializacion', 'precio_sin_impuestos', 'precio_con_impuestos', 'volumen', 'precio_surtidor', 'no_novimientos', 'exentos']
2025
['fecha', 'periodo', 'operador', 'nro_inscripcion', 'bandera', 'fecha_de_baja', 'cuit', 'tipo_negocio', 'direccion', 'localidad', 'provincia', 'producto', 'canal_de_comercializacion', 'precio_sin_impuestos', 'precio_con_impuestos', 'volumen', 'precio_surtidor', 'no_movimientos', 'excentos', 'impuesto_combustible_liquidos', 'impuesto_dioxido_carbono', 'tasa_vial', 'tasa_municipal', 'ingresos_brutos', 'iva', 'fondo_fiduciario_GNC']

2025 dataset introduces date and period instead of year and month plus seven new fields that describe different taxes, and -apparently- change "no_novimientos" and "exentos" to "no_movimientos" and "excentos".

### 2025 period column inspection

In [58]:
prices_25['periodo'].unique()

array(['2024/12', '2025/01', '2025/02', '2025/03', '2025/04', '2025/05',
       '2025/06', '2025/07', '2025/08', '2025/09', '2025/10', '2025/11',
       '2025/12', '2026/01', '2026/02', '2026/03', '2026/04', '2026/05',
       '2026/06', '2026/07'], dtype=object)

"2025" dataset covers from december-24 up to july-26. Since the scope of the project is bounded to the four most recent completed years (2022-2025), 2026 records have to be excluded. Besides that, a futher inspection -and comparison- of december 2024 is performed later in this notebook.

#### Year and month columns extraction in prices-25

In [59]:
prices_25['anio'] = prices_25['periodo'].str.split("/", n=1).str[0]
prices_25['mes'] = prices_25['periodo'].str.split("/", n=1).str[1]

### Year & month: coverage and missingness

In [60]:
for year, df in prices_dict.items():
    print(f"{year}:")
    print(f"Shape: {df.shape}")
    print(f"Year unique values: {df['anio'].unique()}")
    print(f"Month unique values: {df['mes'].unique()}")
    print(f"Null year values: {df['anio'].isna().sum()}")
    print(f"Null month values: {df['mes'].isna().sum()}")
    print("==="*15)

2022:
Shape: (261473, 19)
Year unique values: [2022]
Month unique values: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Null year values: 0
Null month values: 0
=============================================
2023:
Shape: (259806, 19)
Year unique values: [2023]
Month unique values: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Null year values: 0
Null month values: 0
=============================================
2024:
Shape: (256798, 19)
Year unique values: [2024]
Month unique values: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Null year values: 0
Null month values: 0
=============================================
2025:
Shape: (431173, 28)
Year unique values: ['2024' '2025' '2026']
Month unique values: ['12' '01' '02' '03' '04' '05' '06' '07' '08' '09' '10' '11']
Null year values: 0
Null month values: 0
=============================================

The first three datasets don't have year overlapping, and every row in all four datasets have a correct non-null year value.

Besides the fact of the last datasets month and year values being strings, there is no other inconsistency regarding to the compatibility between datasets.

### Data types

In [61]:
dtypes_22_24 = pd.concat([df.dtypes.rename(year) for year, df in prices_dict.items()], axis=1, join="outer")
dtypes_22_24

                                  2022     2023     2024     2025
anio                             int64    int64    int64   object
mes                              int64    int64    int64   object
operador                        object   object   object   object
nro_inscripcion                  int64    int64    int64    int64
bandera                         object   object   object   object
fecha_de_baja                   object   object   object   object
cuit                            object   object   object   object
tipo_negocio                    object   object   object   object
direccion                       object   object   object   object
localidad                       object   object   object   object
provincia                       object   object   object   object
producto                        object   object   object   object
canal_de_comercializacion       object   object   object   object
precio_sin_impuestos           float64  float64  float64  float64
precio_con_impuestos           float64  float64  float64  float64
volumen                        float64  float64  float64  float64
precio_surtidor                float64  float64  float64  float64
no_novimientos                  object   object   object      NaN
exentos                         object   object   object      NaN
fecha                              NaN      NaN      NaN   object
periodo                            NaN      NaN      NaN   object
no_movimientos                     NaN      NaN      NaN   object
excentos                           NaN      NaN      NaN   object
impuesto_combustible_liquidos      NaN      NaN      NaN  float64
impuesto_dioxido_carbono           NaN      NaN      NaN  float64
tasa_vial                          NaN      NaN      NaN  float64
tasa_municipal                     NaN      NaN      NaN  float64
ingresos_brutos                    NaN      NaN      NaN  float64
iva                                NaN      NaN      NaN  float64
fondo_fiduciario_GNC               NaN      NaN      NaN  float64

`fecha_de_baja` and `fecha` (from prices-25) are expected to be date columns, but registered as object. And, as seen above, prices-25 `anio` and `mes` remain as object, while expected as integers.

#### Prices-25 year & month: dtype correction

In [62]:
for col in ['anio', 'mes']:
    prices_25[col] = prices_25[col].astype('int64')
    print(f"{col} dtype: {prices_25[col].dtype}")
    print(f"{col} null values: {prices_25[col].isna().sum()}")

anio dtype: int64
anio null values: 0
mes dtype: int64
mes null values: 0

### Canonical naming of `no_movimientos` and `exentos`.

In [63]:
for year, df in prices_dict.items():
    if year != "2025":
        print(year)
        print(f"no_novimientos values: {df['no_novimientos'].unique()}")
        print(f"exentos values: {df['exentos'].unique()}\n" + "==="*12)
    else:
        print(year)
        print(f"no_movimientos values: {df['no_movimientos'].unique()}")
        print(f"excentos values: {df['excentos'].unique()}\n" + "==="*12)

2022
no_novimientos values: ['NO' 'SI']
exentos values: ['f' 't' nan]
====================================
2023
no_novimientos values: ['NO' 'SI']
exentos values: ['f' nan 't']
====================================
2024
no_novimientos values: ['NO' 'SI']
exentos values: ['f' nan 't']
====================================
2025
no_movimientos values: ['NO' 'SI']
excentos values: ['f' nan 't']
====================================

We can confirm that these columns correspond to the same information.

Therefore, we can rename this fields to an only canonical name.

#### Column renaming
* Prices 22-24: `no_novimientos` -> `no_movimientos`
* Prices 25: `excentos` -> `exentos`

In [64]:
for year, df in prices_dict.items():
    if year != "2025":
        df.rename(columns={"no_novimientos": "no_movimientos"}, inplace=True)
    else:
        df.rename(columns={"excentos": "exentos"}, inplace=True)

### Duplicated rows

#### Full row

In [65]:
for year, df in prices_dict.items():
    print(year)
    print(f"Duplicated count: {df.duplicated().sum()}\n" + "==="*12)
duplicates = sum([df.duplicated().sum() for df in prices_dict.values()])
print(f"Total full row duplicates: {duplicates}")

2022
Duplicated count: 3
====================================
2023
Duplicated count: 5
====================================
2024
Duplicated count: 6
====================================
2025
Duplicated count: 14
====================================
Total full row duplicates: 28

#### Candidate key

In [66]:
print("Candidate key exploration")

eess_key = ['nro_inscripcion']

eess_attr = ['bandera', 'operador', 'tipo_negocio', 'provincia' , 'localidad', 'direccion']

num_eess_keys = sum([len(df[eess_key].drop_duplicates()) for df in prices_dict.values()])

print(f"\nNumber of keys ({eess_key}) \nwith more than one unique value of:")
print("==="*10)
for attr in eess_attr:
    n = 0
    for year, df in prices_dict.items():
        count = df.groupby(eess_key)[attr].nunique()
        n += len(count[count > 1])
    print(f"{attr:15}: {n}")
    print("==="*10)

print(f"Unique keys: {num_eess_keys}")

Candidate key exploration

Number of keys (['nro_inscripcion'])
with more than one unique value of:
==============================
bandera        : 1236
==============================
operador       : 0
==============================
tipo_negocio   : 0
==============================
provincia      : 0
==============================
localidad      : 0
==============================
direccion      : 0
==============================
Unique keys: 22144

In [67]:
period_key = ['anio', 'mes', 'nro_inscripcion']

multi_bandera = 0
for df in prices_dict.values():
    count = df.groupby(period_key)['bandera'].nunique()
    multi_bandera += len(count[count > 1])
num_keys = sum([len(df[period_key].drop_duplicates()) for df in prices_dict.values()])

print(f"Number of keys ({period_key}) \nwith more than unique value of 'bandera': {multi_bandera}")
print(f"Unique keys: {num_keys}")

Number of keys (['anio', 'mes', 'nro_inscripcion'])
with more than unique value of 'bandera': 6
Unique keys: 299431

In [68]:
instance_attr = ['canal_de_comercializacion', 'producto', 'exentos']

print("Possible instance attributes inspection")
print(f"\nPercentage of keys ({period_key}) \nwith more than one unique value of:")
print("==="*13)
for attr in instance_attr:
    n = 0
    for df in prices_dict.values():
        count = df.groupby(period_key)[attr].nunique()
        n += len(count[count > 1])
    print(f"{attr:28}: {100 * n / num_keys:.2f}%")
    print("==="*13)
print(f"Unique keys (denominator): {num_keys}")

Possible instance attributes inspection

Percentage of keys (['anio', 'mes', 'nro_inscripcion'])
with more than one unique value of:
=======================================
canal_de_comercializacion   : 11.97%
=======================================
producto                    : 83.85%
=======================================
exentos                     : 2.74%
=======================================
Unique keys (denominator): 299431

In [69]:
cand_key = ['anio', 'mes', 'nro_inscripcion', 'producto', 'canal_de_comercializacion', 'exentos']

print("Number of duplicates by incremental composite key.")
print(f"Key: {cand_key[:2]}\n" + "==="*15)
for i in range(len(cand_key)):
    if i < 2: continue
    n = 0
    for df in prices_dict.values():
        n += df.duplicated(subset=cand_key[:i+1]).sum()
    print(f"+ {cand_key[2:i+1]}")
    print(f"Duplicates: {n}\n" + "==="*15)
print(f"Full row duplicates: {duplicates}")

Number of duplicates by incremental composite key.
Key: ['anio', 'mes']
=============================================
+ ['nro_inscripcion']
Duplicates: 909819
=============================================
+ ['nro_inscripcion', 'producto']
Duplicates: 128941
=============================================
+ ['nro_inscripcion', 'producto', 'canal_de_comercializacion']
Duplicates: 579
=============================================
+ ['nro_inscripcion', 'producto', 'canal_de_comercializacion', 'exentos']
Duplicates: 29
=============================================
Full row duplicates: 28

### December 2024 inspection

In [70]:
selected_columns = [
    'anio',
    'mes',
    'cuit',
    'bandera',
    'operador',
    'nro_inscripcion',
    'provincia',
    'localidad',
    'direccion',
    'tipo_negocio',
    'canal_de_comercializacion',
    'producto',
    'volumen',
    'precio_sin_impuestos',
    'precio_con_impuestos',
    'precio_surtidor',
    'exentos',
    'fecha_de_baja',
    'no_movimientos'
]
comparison_columns = [col for col in selected_columns if col not in ('fecha_de_baja')]

In [71]:
prices_dic24_1 = prices_24[(prices_24['anio']==2024) & (prices_24['mes']==12)][selected_columns]
prices_dic24_2 = prices_25[(prices_25['anio']==2024) & (prices_25['mes']==12)][selected_columns]
print(f"Number of rows\nPrices-24: {prices_dic24_1.shape[0]} \nPrices-25: {prices_dic24_2.shape[0]} \n" + "==="*15)

intersection = pd.merge(prices_dic24_1, prices_dic24_2, how="inner")
print(f"Number of exact duplicates between dataframes: {intersection.shape[0]}\n" + "==="*15)

intersected_keys = pd.merge(prices_dic24_1[cand_key], prices_dic24_2[cand_key], how="inner")
print(f"Number of duplicated keys between dataframes: {intersected_keys.shape[0]}\n" + "==="*15)

intersection_no_baja = pd.merge(prices_dic24_1[comparison_columns], prices_dic24_2[comparison_columns], how="inner")
print(f"Number of matching rows excluding fecha_de_baja: {intersection_no_baja.shape[0]}\n" + "==="*15)

Number of rows
Prices-24: 20700
Prices-25: 21601
=============================================
Number of exact duplicates between dataframes: 19139
=============================================
Number of duplicated keys between dataframes: 20686
=============================================
Number of matching rows excluding fecha_de_baja: 19316
=============================================

`fecha_de_baja` is understood as a station attrtibute that may change from null to a date when the event occurs, which could explain the inceremnt from exact duplicates to those that don't consider `fecha_de_baja`.

In [72]:
union = pd.merge(prices_dic24_1, prices_dic24_2, how="outer", indicator=True)
union_duplicated_key = union[union.duplicated(subset=cand_key, keep=False)]

union_dk_no_mov = union_duplicated_key[['_merge', 'no_movimientos']].value_counts()
print("Records with duplicated key between prices-24 and prices-25, with or without movements")
print(f"Prices-24: \n{union_dk_no_mov.loc['left_only']}\n" + "==="*10)
print(f"Prices-25: \n{union_dk_no_mov.loc['right_only']}\n")

Records with duplicated key between prices-24 and prices-25, with or without movements
Prices-24:
no_movimientos
NO    1535
SI      12
Name: count, dtype: int64
==============================
Prices-25:
no_movimientos
NO    1535
SI      12
Name: count, dtype: int64

### Record provenance traceability

In [73]:
union['provenance'] = union['_merge'].map(
    {
    "left_only": "prices_2024", 
    "right_only": "prices_2025", 
    "both": "both_2024_2025"
    }
)

In [74]:
for year, df in prices_dict.items():
    df['provenance'] = f"prices_{year}"

### Data concatenation

In [75]:
final_columns = selected_columns + ['provenance']

In [76]:
final_dataframes = [
    prices_22[final_columns],
    prices_23[final_columns],
    prices_24[prices_24['mes']!=12][final_columns],
    union[final_columns],
    prices_25[prices_25['periodo']!='2024/12'][final_columns],
]

In [77]:
prices = pd.DataFrame(pd.concat(final_dataframes))
n, m = prices.shape
print(f"Resulting dataframe shape: {n} x {m}\n" + "==="*15)
print(f"Number of duplicated full rows: {prices.duplicated().sum()}\n" + "==="*15)
print(f"Number of rows with duplicated keys: {prices.duplicated(subset=cand_key, keep=False).sum()}\n" + "==="*15)

Resulting dataframe shape: 1190111 x 20
=============================================
Number of duplicated full rows: 28
=============================================
Number of rows with duplicated keys: 3151
=============================================

#### Exclusion: 2026 records

In [78]:
print(f"2026 records: {len(prices[prices['anio']==2026])}")

prices = prices[prices['anio']!=2026]
print(f"Resulting rows: {prices.shape[0]}")

2026 records: 148321
Resulting rows: 1041790

#### Exclusion: not "to general public" records

In [79]:
print(f"Records excluding 'Al público': {len(prices[prices['canal_de_comercializacion']!='Al público'])}")

prices = prices[prices['canal_de_comercializacion']=='Al público']
print(f"Resulting rows: {prices.shape[0]}")

Records excluding 'Al público': 159351
Resulting rows: 882439

### Deduplication: full rows

In [80]:
prices = prices.drop_duplicates()
print(f"Resulting rows: {prices.shape[0]}. Duplicated: {prices.duplicated().sum()}")

Resulting rows: 882439. Duplicated: 0

### Flag: duplicated candidate key

In [81]:
prices['duplicated_key'] = prices.duplicated(subset=cand_key, keep=False)
print(f"Resulting rows with duplicated key: {len(prices[prices['duplicated_key']])}")

Resulting rows with duplicated key: 2804

In [82]:
prices['duplicated_key'] = prices.duplicated(subset=cand_key, keep=False)

### Numeric fields: descriptive statistics

In [83]:
prices.describe(percentiles=[0.5])

,anio,mes,nro_inscripcion,volumen,precio_sin_impuestos,precio_con_impuestos,precio_surtidor
count,882439.000000,882439.000000,882439.000000,8.824390e+05,882439.000000,882439.000000,882439.000000
mean,2023.499312,6.502911,5554.274360,1.070164e+04,541.901554,732.350467,741.560657
std,1.117762,3.455712,3403.627869,4.072788e+05,417.735950,573.617624,578.072299
min,2022.000000,1.000000,101.000000,1.000000e-10,0.000100,0.000100,0.000100
50%,2024.000000,6.000000,5765.000000,6.654000e+01,410.100000,518.720000,533.000000
max,2025.000000,12.000000,11518.000000,3.550410e+08,4910.000000,4999.000000,5000.000000

There's no negativeness in the numeric fields, but there are zeros in prices and volume.

#### Main numeric fields: distribution profiling

Volume and price percentiles are inspected to assess distribution shape and extreme values.

In [84]:
main_numeric_cols = [
    'volumen',
    'precio_sin_impuestos',
    'precio_con_impuestos',
    'precio_surtidor'
]

prices[main_numeric_cols].describe(
    percentiles=[.01, .05, .25, .50, .75, .95, .99, .999]
).T

,count,mean,std,min,1%,5%,25%,50%,75%,95%,99%,99.9%,max
volumen,882439.0,10701.637134,407278.760782,1.000000e-10,0.6310,3.9449,26.6600,66.54,160.060,83290.000,149696.58,259791.56200,355041000.0
precio_sin_impuestos,882439.0,541.901554,417.735950,1.000000e-04,44.6200,72.9400,143.5780,410.10,923.338,1204.660,1393.86,1573.22496,4910.0
precio_con_impuestos,882439.0,732.350467,573.617624,1.000000e-04,58.4900,100.2000,192.7105,518.72,1266.085,1660.971,1899.00,2078.00000,4999.0
precio_surtidor,882439.0,741.560657,578.072299,1.000000e-04,59.3938,101.5000,195.9000,533.00,1274.000,1688.000,1921.00,2088.00000,5000.0

### Column missingness

In [85]:
print("Column missing values")
for col in prices.columns:
    print(f"{col:28}: {prices[col].isna().sum()}")

Column missing values
anio                        : 0
mes                         : 0
cuit                        : 0
bandera                     : 0
operador                    : 0
nro_inscripcion             : 0
provincia                   : 0
localidad                   : 0
direccion                   : 0
tipo_negocio                : 0
canal_de_comercializacion   : 0
producto                    : 0
volumen                     : 0
precio_sin_impuestos        : 0
precio_con_impuestos        : 0
precio_surtidor             : 0
exentos                     : 0
fecha_de_baja               : 850885
no_movimientos              : 0
provenance                  : 0
duplicated_key              : 0

`fecha_de_baja` Validation or updating against a more recent station registry remains pending and requires an external source.

### Categorical value profiling

In [86]:
categorical_columns = prices.select_dtypes(include=['object', 'category']).columns
print('Categorical field cardinality:')
for col in categorical_columns:
    print(f"{col:28}: {prices[col].nunique(dropna=False)}")

Categorical field cardinality:
cuit                        : 3589
bandera                     : 23
operador                    : 4020
provincia                   : 24
localidad                   : 1140
direccion                   : 5352
tipo_negocio                : 12
canal_de_comercializacion   : 1
producto                    : 8
exentos                     : 2
fecha_de_baja               : 273
no_movimientos              : 1
provenance                  : 5

In [87]:
for col in categorical_columns:
    n = prices[col].nunique(dropna=False)
    if n < 10:
        print(f"Column {col} has {n} distinct values. Category distribution:")
        display(prices[col].value_counts(dropna=False).reset_index())
    else:
        continue

Column canal_de_comercializacion has 1 distinct values. Category distribution:

  canal_de_comercializacion   count
0                Al público  882439

Column producto has 8 distinct values. Category distribution:

                           producto   count
0   Nafta (súper) entre 92 y 95 Ron  201118
1                   Gas Oil Grado 3  196571
2                   Gas Oil Grado 2  193060
3  Nafta (premium) de más de 95 Ron  190481
4                               GNC   92107
5                          Kerosene    6809
6        Nafta (común) hasta 92 Ron    2127
7                              GLPA     166

Column exentos has 2 distinct values. Category distribution:

  exentos   count
0       f  858730
1       t   23709

Column no_movimientos has 1 distinct values. Category distribution:

  no_movimientos   count
0             NO  882439

Column provenance has 5 distinct values. Category distribution:

       provenance   count
0     prices_2025  222238
1     prices_2022  220815
2     prices_2023  220333
3     prices_2024  202701
4  both_2024_2025   16352

#### Text normalization: cardinality comparison
In order to prove if there is a reduction (or not) of the cardinality after text normalization (remove accents, normalize casing, strip spaces on the edges and delete multiple spaces between words)

In [88]:
import unicodedata
import re

def remove_accents(text: str) -> str:
    normalized = unicodedata.normalize("NFKD", text)
    return "".join(
        char for char in normalized if not unicodedata.combining(char)
    )

def normalize_text(text: str) -> str:
    """Normalize a non-null text value without changing its semantics."""
    if pd.isna(text):
        return text
    text = str(text).strip().lower()
    text = remove_accents(text)
    text = re.sub(r"\s+", " ", text)
    return text

In [89]:
prices_norm_txt = prices.copy()
for col in categorical_columns:
    prices_norm_txt[col] = prices[col].apply(normalize_text)

In [90]:
print("Text normalization cardinality test:\n" + " "*15 + "Before | After")
for col in prices.select_dtypes(include=['object']).columns:
    if col != 'fecha_de_baja' and prices[col].nunique() >= 10:
        before = prices[col].nunique()
        after = prices_norm_txt[col].nunique()
        print(f"{col:15}{before:7}|{after:6} diff={before-after}")

Text normalization cardinality test:
               Before | After
cuit              3589|  3589 diff=0
bandera             23|    23 diff=0
operador          4020|  4002 diff=18
provincia           24|    24 diff=0
localidad         1140|  1140 diff=0
direccion         5352|  5308 diff=44
tipo_negocio        12|    12 diff=0

#### Missing text values variants

In [91]:
null_text_variants = ["", "nan", "n/d"]

print(" "*27 + "  Nulls  | Null variants")
for col in categorical_columns:
    null_variants = prices_norm_txt[col].isin(null_text_variants).sum()
    nulls = prices_norm_txt[col].isna().sum()
    print(f"{col:26}: {nulls:7} | {null_variants}")

                             Nulls  | Null variants
cuit                      :       0 | 0
bandera                   :       0 | 0
operador                  :       0 | 0
provincia                 :       0 | 0
localidad                 :       0 | 0
direccion                 :       0 | 0
tipo_negocio              :       0 | 497
canal_de_comercializacion :       0 | 0
producto                  :       0 | 0
exentos                   :       0 | 0
fecha_de_baja             :  850885 | 0
no_movimientos            :       0 | 0
provenance                :       0 | 0

#### Cardinality reduction inspection

### Duplicated candidate key: numeric differences

Within-key volume and price differences are inspected to inform the consolidation tolerance and technique. Each price field is compared across records sharing a key.

In [92]:
duplicated = prices[prices['duplicated_key']].copy()

duplicated_numeric_cols = [
    'volumen',
    'precio_sin_impuestos',
    'precio_con_impuestos',
    'precio_surtidor'
]

duplicated_group_sizes = (
    duplicated
    .groupby(cand_key, dropna=False, observed=True)
    .size()
    .value_counts()
    .sort_index()
)

print('Number of records per duplicated candidate key:')
display(duplicated_group_sizes)

Number of records per duplicated candidate key:

2    1402
Name: count, dtype: int64

#### Within-key numeric ranges

In [93]:
duplicated_ranges = (
    duplicated
    .groupby(cand_key, dropna=False, observed=True)[duplicated_numeric_cols]
    .agg(['min', 'max'])
)

for col in duplicated_numeric_cols:
    duplicated_ranges[(col, 'diff')] = (
        duplicated_ranges[(col, 'max')] -
        duplicated_ranges[(col, 'min')]
    )

duplicated_ranges

                                                                                                volumen  \
                                                                                                    min
anio mes nro_inscripcion producto                         canal_de_comercializacion exentos
2024 12  148             GNC                              Al público                f        44534.0000
         162             Gas Oil Grado 2                  Al público                f           19.5700
                         Gas Oil Grado 3                  Al público                f            6.1000
                         Nafta (premium) de más de 95 Ron Al público                f            4.6900
                         Nafta (súper) entre 92 y 95 Ron  Al público                f           17.9000
...                                                                                                 ...
         11235           GNC                              Al público                f        18833.0000
         11236           Gas Oil Grado 2                  Al público                f           33.3024
                         Gas Oil Grado 3                  Al público                f           37.7995
                         Nafta (premium) de más de 95 Ron Al público                f           62.1979
                         Nafta (súper) entre 92 y 95 Ron  Al público                f          174.2280

                                                                                                        \
                                                                                                   max
anio mes nro_inscripcion producto                         canal_de_comercializacion exentos
2024 12  148             GNC                              Al público                f         52289.00
         162             Gas Oil Grado 2                  Al público                f            19.57
                         Gas Oil Grado 3                  Al público                f             6.10
                         Nafta (premium) de más de 95 Ron Al público                f             4.69
                         Nafta (súper) entre 92 y 95 Ron  Al público                f            17.90
...                                                                                                ...
         11235           GNC                              Al público                f         18833.00
         11236           Gas Oil Grado 2                  Al público                f         28000.00
                         Gas Oil Grado 3                  Al público                f         32858.00
                         Nafta (premium) de más de 95 Ron Al público                f         60395.00
                         Nafta (súper) entre 92 y 95 Ron  Al público                f        172787.00

                                                                                            precio_sin_impuestos  \
                                                                                                             min
anio mes nro_inscripcion producto                         canal_de_comercializacion exentos
2024 12  148             GNC                              Al público                f                    458.678
         162             Gas Oil Grado 2                  Al público                f                    657.650
                         Gas Oil Grado 3                  Al público                f                    833.350
                         Nafta (premium) de más de 95 Ron Al público                f                    817.735
                         Nafta (súper) entre 92 y 95 Ron  Al público                f                    622.700
...                                                                                                          ...
         11235           GNC                              Al público                f                    454.463
         11236           Gas Oil Grado 2                  Al público                f                    805.350
                         Gas Oil Grado 3                  Al público                f                   1006.640
                         Nafta (premium) de más de 95 Ron Al público                f                    945.370
                         Nafta (súper) entre 92 y 95 Ron  Al público                f                    786.000

                                                                                                       \
                                                                                                  max
anio mes nro_inscripcion producto                         canal_de_comercializacion exentos
2024 12  148             GNC                              Al público                f         458.680
         162             Gas Oil Grado 2                  Al público                f         809.930
                         Gas Oil Grado 3                  Al público                f         979.355
                         Nafta (premium) de más de 95 Ron Al público                f        1005.560
                         Nafta (súper) entre 92 y 95 Ron  Al público                f         807.214
...                                                                                               ...
         11235           GNC                              Al público                f         454.463
         11236           Gas Oil Grado 2                  Al público                f        1011.920
                         Gas Oil Grado 3                  Al público                f        1191.660
                         Nafta (premium) de más de 95 Ron Al público                f         975.730
                         Nafta (súper) entre 92 y 95 Ron  Al público                f        1165.690

                                                                                            precio_con_impuestos  \
                                                                                                             min
anio mes nro_inscripcion producto                         canal_de_comercializacion exentos
2024 12  148             GNC                              Al público                f                      555.0
         162             Gas Oil Grado 2                  Al público                f                     1203.0
                         Gas Oil Grado 3                  Al público                f                     1405.0
                         Nafta (premium) de más de 95 Ron Al público                f                     1419.0
                         Nafta (súper) entre 92 y 95 Ron  Al público                f                     1183.0
...                                                                                                          ...
         11235           GNC                              Al público                f                      549.9
         11236           Gas Oil Grado 2                  Al público                f                     1146.0
                         Gas Oil Grado 3                  Al público                f                     1387.0
                         Nafta (premium) de más de 95 Ron Al público                f                     1420.0
                         Nafta (súper) entre 92 y 95 Ron  Al público                f                     1159.0

                                                                                                     \
                                                                                                max
anio mes nro_inscripcion producto                         canal_de_comercializacion exentos
2024 12  148             GNC                              Al público                f         555.0
         162             Gas Oil Grado 2                  Al público                f        1225.0
                         Gas Oil Grado 3                  Al público                f        1430.0
                         Nafta (premium) de más de 95 Ron Al público                f        1444.0
                         Nafta (súper) entre 92 y 95 Ron  Al público                f        1204.0
...                                                                                             ...
         11235           GNC                              Al público                f         549.9
         11236           Gas Oil Grado 2                  Al público                f        1167.0
                         Gas Oil Grado 3                  Al público                f        1412.0
                         Nafta (premium) de más de 95 Ron Al público                f        1445.0
                         Nafta (súper) entre 92 y 95 Ron  Al público                f        1180.0

                                                                                            precio_surtidor  \
                                                                                                        min
anio mes nro_inscripcion producto                         canal_de_comercializacion exentos
2024 12  148             GNC                              Al público                f                 555.0
         162             Gas Oil Grado 2                  Al público                f                1203.0
                         Gas Oil Grado 3                  Al público                f                1405.0
                         Nafta (premium) de más de 95 Ron Al público                f                1419.0
                         Nafta (súper) entre 92 y 95 Ron  Al público                f                1183.0
...                                                                                                     ...
         11235           GNC                              Al público                f                 549.9
         11236           Gas Oil Grado 2                  Al público                f                1146.0
                         Gas Oil Grado 3                  Al público                f                1387.0
                         Nafta (premium) de más de 95 Ron Al público                f                1420.0
                         Nafta (súper) entre 92 y 95 Ron  Al público                f                1159.0

                                                                                                     \
                                                                                                max
anio mes nro_inscripcion producto                         canal_de_comercializacion exentos
2024 12  148             GNC                              Al público                f         555.0
         162             Gas Oil Grado 2                  Al público                f        1203.0
                         Gas Oil Grado 3                  Al público                f        1430.0
                         Nafta (premium) de más de 95 Ron Al público                f        1444.0
                         Nafta (súper) entre 92 y 95 Ron  Al público                f        1204.0
...                                                                                             ...
         11235           GNC                              Al público                f         549.9
         11236           Gas Oil Grado 2                  Al público                f        1167.0
                         Gas Oil Grado 3                  Al público                f        1412.0
                         Nafta (premium) de más de 95 Ron Al público                f        1445.0
                         Nafta (súper) entre 92 y 95 Ron  Al público                f        1180.0

                                                                                                 volumen  \
                                                                                                    diff
anio mes nro_inscripcion producto                         canal_de_comercializacion exentos
2024 12  148             GNC                              Al público                f          7755.0000
         162             Gas Oil Grado 2                  Al público                f             0.0000
                         Gas Oil Grado 3                  Al público                f             0.0000
                         Nafta (premium) de más de 95 Ron Al público                f             0.0000
                         Nafta (súper) entre 92 y 95 Ron  Al público                f             0.0000
...                                                                                                  ...
         11235           GNC                              Al público                f             0.0000
         11236           Gas Oil Grado 2                  Al público                f         27966.6976
                         Gas Oil Grado 3                  Al público                f         32820.2005
                         Nafta (premium) de más de 95 Ron Al público                f         60332.8021
                         Nafta (súper) entre 92 y 95 Ron  Al público                f        172612.7720

                                                                                            precio_sin_impuestos  \
                                                                                                            diff
anio mes nro_inscripcion producto                         canal_de_comercializacion exentos
2024 12  148             GNC                              Al público                f                      0.002
         162             Gas Oil Grado 2                  Al público                f                    152.280
                         Gas Oil Grado 3                  Al público                f                    146.005
                         Nafta (premium) de más de 95 Ron Al público                f                    187.825
                         Nafta (súper) entre 92 y 95 Ron  Al público                f                    184.514
...                                                                                                          ...
         11235           GNC                              Al público                f                      0.000
         11236           Gas Oil Grado 2                  Al público                f                    206.570
                         Gas Oil Grado 3                  Al público                f                    185.020
                         Nafta (premium) de más de 95 Ron Al público                f                     30.360
                         Nafta (súper) entre 92 y 95 Ron  Al público                f                    379.690

                                                                                            precio_con_impuestos  \
                                                                                                            diff
anio mes nro_inscripcion producto                         canal_de_comercializacion exentos
2024 12  148             GNC                              Al público                f                        0.0
         162             Gas Oil Grado 2                  Al público                f                       22.0
                         Gas Oil Grado 3                  Al público                f                       25.0
                         Nafta (premium) de más de 95 Ron Al público                f                       25.0
                         Nafta (súper) entre 92 y 95 Ron  Al público                f                       21.0
...                                                                                                          ...
         11235           GNC                              Al público                f                        0.0
         11236           Gas Oil Grado 2                  Al público                f                       21.0
                         Gas Oil Grado 3                  Al público                f                       25.0
                         Nafta (premium) de más de 95 Ron Al público                f                       25.0
                         Nafta (súper) entre 92 y 95 Ron  Al público                f                       21.0

                                                                                            precio_surtidor
                                                                                                       diff
anio mes nro_inscripcion producto                         canal_de_comercializacion exentos
2024 12  148             GNC                              Al público                f                   0.0
         162             Gas Oil Grado 2                  Al público                f                   0.0
                         Gas Oil Grado 3                  Al público                f                  25.0
                         Nafta (premium) de más de 95 Ron Al público                f                  25.0
                         Nafta (súper) entre 92 y 95 Ron  Al público                f                  21.0
...                                                                                                     ...
         11235           GNC                              Al público                f                   0.0
         11236           Gas Oil Grado 2                  Al público                f                  21.0
                         Gas Oil Grado 3                  Al público                f                  25.0
                         Nafta (premium) de más de 95 Ron Al público                f                  25.0
                         Nafta (súper) entre 92 y 95 Ron  Al público                f                  21.0

[1402 rows x 12 columns]

#### Numeric difference distribution

In [94]:
diff_cols = [(col, 'diff') for col in duplicated_numeric_cols]

duplicated_ranges[diff_cols].describe(
    percentiles=[.25, .50, .75, .90, .95, .99]
).T

,,count,mean,std,min,25%,50%,75%,90%,95%,99%,max
volumen,diff,1402.0,5219.959740,27166.674335,0.0,0.0,0.0,0.0000,4.5356,29722.49280,161621.69049,383660.200
precio_sin_impuestos,diff,1402.0,34.746558,83.704030,0.0,0.0,0.0,16.9765,137.6168,209.18815,363.28980,829.004
precio_con_impuestos,diff,1402.0,12.939422,83.459770,0.0,0.0,0.0,0.0000,3.5620,39.84050,316.90050,1448.550
precio_surtidor,diff,1402.0,8.958490,86.944273,0.0,0.0,0.0,0.0000,0.0000,10.95000,202.69000,1448.550

#### Duplicated records inspection

In [95]:
duplicated.sort_values(cand_key)[
    cand_key
    + duplicated_numeric_cols
    + ['no_movimientos', 'provenance']
].head(50)

,anio,mes,nro_inscripcion,producto,canal_de_comercializacion,exentos,volumen,precio_sin_impuestos,precio_con_impuestos,precio_surtidor,no_movimientos,provenance
14769,2024,12,148,GNC,Al público,f,44534.0000,458.680,555.000,555.0,NO,prices_2025
14770,2024,12,148,GNC,Al público,f,52289.0000,458.678,555.000,555.0,NO,prices_2024
555,2024,12,162,Gas Oil Grado 2,Al público,f,19.5700,657.650,1203.000,1203.0,NO,prices_2024
556,2024,12,162,Gas Oil Grado 2,Al público,f,19.5700,809.930,1225.000,1203.0,NO,prices_2025
557,2024,12,162,Gas Oil Grado 3,Al público,f,6.1000,833.350,1405.000,1405.0,NO,prices_2024
558,2024,12,162,Gas Oil Grado 3,Al público,f,6.1000,979.355,1430.000,1430.0,NO,prices_2025
559,2024,12,162,Nafta (premium) de más de 95 Ron,Al público,f,4.6900,817.735,1419.000,1419.0,NO,prices_2024
560,2024,12,162,Nafta (premium) de más de 95 Ron,Al público,f,4.6900,1005.560,1444.000,1444.0,NO,prices_2025
561,2024,12,162,Nafta (súper) entre 92 y 95 Ron,Al público,f,17.9000,622.700,1183.000,1183.0,NO,prices_2024
562,2024,12,162,Nafta (súper) entre 92 y 95 Ron,Al público,f,17.9000,807.214,1204.000,1204.0,NO,prices_2025
10803,2024,12,175,GNC,Al público,f,38488.0000,429.802,529.000,529.0,NO,prices_2025
10804,2024,12,175,GNC,Al público,f,38488.0000,491.652,529.000,529.0,NO,prices_2024
8966,2024,12,180,Nafta (premium) de más de 95 Ron,Al público,f,20.7100,993.216,1212.550,1213.0,NO,prices_2024
8967,2024,12,180,Nafta (premium) de más de 95 Ron,Al público,f,20.7100,993.220,1212.550,1213.0,NO,prices_2025
8968,2024,12,180,Nafta (súper) entre 92 y 95 Ron,Al público,f,123.0100,776.929,950.790,953.0,NO,prices_2025
8969,2024,12,180,Nafta (súper) entre 92 y 95 Ron,Al público,f,123.0100,776.929,950.791,953.0,NO,prices_2024
6967,2024,12,205,Gas Oil Grado 2,Al público,f,95.6500,884.550,1215.000,1215.0,NO,prices_2025
6968,2024,12,205,Gas Oil Grado 2,Al público,f,95.6500,917.190,1215.000,1215.0,NO,prices_2024
6969,2024,12,205,Gas Oil Grado 3,Al público,f,44.0600,1056.380,1419.000,1419.0,NO,prices_2025
6970,2024,12,205,Gas Oil Grado 3,Al público,f,44.0600,1088.250,1419.000,1419.0,NO,prices_2024
6971,2024,12,205,Nafta (premium) de más de 95 Ron,Al público,f,14.8200,1032.270,1440.000,1440.0,NO,prices_2025
6972,2024,12,205,Nafta (premium) de más de 95 Ron,Al público,f,14.8200,1070.050,1440.000,1440.0,NO,prices_2024
6973,2024,12,205,Nafta (súper) entre 92 y 95 Ron,Al público,f,35.1100,834.750,1201.000,1201.0,NO,prices_2025
6974,2024,12,205,Nafta (súper) entre 92 y 95 Ron,Al público,f,35.1200,872.290,1201.000,1201.0,NO,prices_2024
6831,2024,12,276,GNC,Al público,f,120661.0000,412.340,517.060,510.0,NO,prices_2025
6832,2024,12,276,GNC,Al público,f,120661.0000,412.340,517.182,510.0,NO,prices_2024
6028,2024,12,382,Gas Oil Grado 2,Al público,f,48.4843,840.594,1123.000,1123.0,NO,prices_2025
6029,2024,12,382,Gas Oil Grado 2,Al público,f,48.8430,840.594,1123.000,1123.0,NO,prices_2024
6030,2024,12,382,Gas Oil Grado 3,Al público,f,67.5130,1046.080,1368.000,1368.0,NO,prices_2025
6031,2024,12,382,Gas Oil Grado 3,Al público,f,67.5130,1046.080,1368.000,1369.0,NO,prices_2024
6219,2024,12,481,Gas Oil Grado 2,Al público,f,2.7950,743.400,1239.000,1239.0,NO,prices_2024
6220,2024,12,481,Gas Oil Grado 2,Al público,f,2.7950,1053.510,1239.000,1239.0,NO,prices_2025
6221,2024,12,481,Gas Oil Grado 3,Al público,f,3.4780,876.000,1460.000,1460.0,NO,prices_2024
6222,2024,12,481,Gas Oil Grado 3,Al público,f,3.4780,1302.510,1460.000,1460.0,NO,prices_2025
6223,2024,12,481,Nafta (premium) de más de 95 Ron,Al público,f,3.4360,890.400,1484.000,1484.0,NO,prices_2024
6224,2024,12,481,Nafta (premium) de más de 95 Ron,Al público,f,3.4360,1312.000,1484.000,1484.0,NO,prices_2025
6225,2024,12,481,Nafta (súper) entre 92 y 95 Ron,Al público,f,9.4340,731.400,1219.000,1219.0,NO,prices_2024
6226,2024,12,481,Nafta (súper) entre 92 y 95 Ron,Al público,f,9.4340,1011.000,1219.000,1219.0,NO,prices_2025
13057,2024,12,502,Nafta (premium) de más de 95 Ron,Al público,t,27.4400,1165.000,1411.000,1411.0,NO,prices_2025
13058,2024,12,502,Nafta (premium) de más de 95 Ron,Al público,t,27.4400,1165.340,1411.000,1411.0,NO,prices_2024
2063,2024,12,596,Gas Oil Grado 2,Al público,f,12.5780,903.550,1238.000,1238.0,NO,prices_2025
2064,2024,12,596,Gas Oil Grado 2,Al público,f,12.5780,911.900,1238.000,1238.0,NO,prices_2024
2065,2024,12,596,Gas Oil Grado 3,Al público,f,9.3300,1089.500,1463.000,1463.0,NO,prices_2025
2066,2024,12,596,Gas Oil Grado 3,Al público,f,9.3300,1097.860,1463.000,1463.0,NO,prices_2024
2067,2024,12,596,Nafta (premium) de más de 95 Ron,Al público,f,7.7560,1009.950,1413.000,1413.0,NO,prices_2025
2068,2024,12,596,Nafta (premium) de más de 95 Ron,Al público,f,7.7560,1019.640,1413.000,1413.0,NO,prices_2024
2069,2024,12,596,Nafta (súper) entre 92 y 95 Ron,Al público,f,72.8780,810.770,1172.000,1172.0,NO,prices_2025
2070,2024,12,596,Nafta (súper) entre 92 y 95 Ron,Al público,f,72.8780,820.470,1172.000,1172.0,NO,prices_2024
14725,2024,12,720,Gas Oil Grado 2,Al público,f,390.4300,882.420,1207.000,1207.0,NO,prices_2024
14729,2024,12,720,Gas Oil Grado 2,Al público,f,390.4300,882.420,1207.000,1207.0,NO,prices_2025

#### Consolidation criteria

Consolidation tolerance and technique remain to be defined after executing and reviewing the within-key difference inspection.

Possible techniques to assess:
- first
- last
- mean

## Final validation

In [96]:
price_cols = ['precio_con_impuestos', 'precio_sin_impuestos', 'precio_surtidor']
cat_cols = ['canal_de_comercializacion', 'producto']

prices_wo_price = prices[(prices[price_cols] == 0).any(axis=1)]
prices_wo_cats = prices[(prices[cat_cols] == "N/D").any(axis=1)]

print("Rows where:")
print(f"-any price column is zero: {len(prices_wo_price)}")
print(f"-volume column is zero: {len(prices[prices['volumen'] == 0])}")
print(f"-null exentos value: {len(prices[prices['exentos'].isna()])}")
print(f"-any instance category is null: {len(prices_wo_cats)}")
print(f"\nTotal rows: {len(prices)}")

Rows where:
-any price column is zero: 0
-volume column is zero: 0
-null exentos value: 0
-any instance category is null: 0

Total rows: 882439

In [97]:
prices.to_csv("data/interim/prices.csv", index=False)