# Data Quality Audit

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

prices_22 = pd.read_csv('data/raw/precios-eess-2022.csv')
prices_23 = pd.read_csv('data/raw/precios-eess-2023.csv')
prices_24 = pd.read_csv('data/raw/precios-eess-2024.csv')
prices_25 = pd.read_csv('data/raw/precios-eess-2025-.csv')

In [2]:
prices_dict = {
    '2022': prices_22,
    '2023': prices_23,
    '2024': prices_24,
    '2025': prices_25
}

### Column names

In [3]:
for year, df in prices_dict.items():
    print(year)
    print(list(df.columns))

2022
['anio', 'mes', 'operador', 'nro_inscripcion', 'bandera', 'fecha_de_baja', 'cuit', 'tipo_negocio', 'direccion', 'localidad', 'provincia', 'producto', 'canal_de_comercializacion', 'precio_sin_impuestos', 'precio_con_impuestos', 'volumen', 'precio_surtidor', 'no_novimientos', 'exentos']
2023
['anio', 'mes', 'operador', 'nro_inscripcion', 'bandera', 'fecha_de_baja', 'cuit', 'tipo_negocio', 'direccion', 'localidad', 'provincia', 'producto', 'canal_de_comercializacion', 'precio_sin_impuestos', 'precio_con_impuestos', 'volumen', 'precio_surtidor', 'no_novimientos', 'exentos']
2024
['anio', 'mes', 'operador', 'nro_inscripcion', 'bandera', 'fecha_de_baja', 'cuit', 'tipo_negocio', 'direccion', 'localidad', 'provincia', 'producto', 'canal_de_comercializacion', 'precio_sin_impuestos', 'precio_con_impuestos', 'volumen', 'precio_surtidor', 'no_novimientos', 'exentos']
2025
['fecha', 'periodo', 'operador', 'nro_inscripcion', 'bandera', 'fecha_de_baja', 'cuit', 'tipo_negocio', 'direccion', 'localidad', 'provincia', 'producto', 'canal_de_comercializacion', 'precio_sin_impuestos', 'precio_con_impuestos', 'volumen', 'precio_surtidor', 'no_movimientos', 'excentos', 'impuesto_combustible_liquidos', 'impuesto_dioxido_carbono', 'tasa_vial', 'tasa_municipal', 'ingresos_brutos', 'iva', 'fondo_fiduciario_GNC']

2025 dataset introduces date and period instead of year and month plus seven new fields that describe different taxes, and -apparently- change "no_novimientos" and "exentos" to "no_movimientos" and "excentos".

### 2025 period column inspection

In [4]:
prices_25['periodo'].unique()

array(['2024/12', '2025/01', '2025/02', '2025/03', '2025/04', '2025/05',
       '2025/06', '2025/07', '2025/08', '2025/09', '2025/10', '2025/11',
       '2025/12', '2026/01', '2026/02', '2026/03', '2026/04', '2026/05',
       '2026/06', '2026/07'], dtype=object)

"2025" dataset covers from december-24 up to july-26. Since the scope of the project is bounded to the four most recent completed years (2022-2025), 2026 records have to be excluded. Besides that, a futher inspection -and comparison- of december 2024 is performed later in this notebook.

#### Year and month columns extraction in prices-25

In [5]:
prices_25['anio'] = prices_25['periodo'].str.split("/", n=1).str[0]
prices_25['mes'] = prices_25['periodo'].str.split("/", n=1).str[1]

### Year & month: coverage and missingness

In [6]:
for year, df in prices_dict.items():
    print(f"{year}:")
    print(f"Shape: {df.shape}")
    print(f"Year unique values: {df['anio'].unique()}")
    print(f"Month unique values: {df['mes'].unique()}")
    print(f"Null year values: {df['anio'].isna().sum()}")
    print("==="*15)

2022:
Shape: (261473, 19)
Year unique values: [2022]
Month unique values: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Null year values: 0
=============================================
2023:
Shape: (259806, 19)
Year unique values: [2023]
Month unique values: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Null year values: 0
=============================================
2024:
Shape: (256798, 19)
Year unique values: [2024]
Month unique values: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Null year values: 0
=============================================
2025:
Shape: (431173, 28)
Year unique values: ['2024' '2025' '2026']
Month unique values: ['12' '01' '02' '03' '04' '05' '06' '07' '08' '09' '10' '11']
Null year values: 0
=============================================

The first three datasets don't have year overlapping, and every row in all four datasets have a correct non-null year value.

Besides the fact of the last datasets month and year values being strings, there is no other inconsistency regarding to the compatibility between datasets.

### Data types

In [7]:
dtypes_22_24 = pd.concat([df.dtypes.rename(year) for year, df in prices_dict.items()], axis=1, join="outer")
dtypes_22_24

                                  2022     2023     2024     2025
anio                             int64    int64    int64   object
mes                              int64    int64    int64   object
operador                        object   object   object   object
nro_inscripcion                  int64    int64    int64    int64
bandera                         object   object   object   object
fecha_de_baja                   object   object   object   object
cuit                            object   object   object   object
tipo_negocio                    object   object   object   object
direccion                       object   object   object   object
localidad                       object   object   object   object
provincia                       object   object   object   object
producto                        object   object   object   object
canal_de_comercializacion       object   object   object   object
precio_sin_impuestos           float64  float64  float64  float64
precio_con_impuestos           float64  float64  float64  float64
volumen                        float64  float64  float64  float64
precio_surtidor                float64  float64  float64  float64
no_novimientos                  object   object   object      NaN
exentos                         object   object   object      NaN
fecha                              NaN      NaN      NaN   object
periodo                            NaN      NaN      NaN   object
no_movimientos                     NaN      NaN      NaN   object
excentos                           NaN      NaN      NaN   object
impuesto_combustible_liquidos      NaN      NaN      NaN  float64
impuesto_dioxido_carbono           NaN      NaN      NaN  float64
tasa_vial                          NaN      NaN      NaN  float64
tasa_municipal                     NaN      NaN      NaN  float64
ingresos_brutos                    NaN      NaN      NaN  float64
iva                                NaN      NaN      NaN  float64
fondo_fiduciario_GNC               NaN      NaN      NaN  float64

fecha_de_baja and fecha (from prices-25) are expected to be date columns, but registered as object. And, as seen above, prices-25 anio and mes remain as object, while expected as integers.

#### Prices-25 year & month: dtype correction

In [8]:
prices_25['anio'] = prices_25['anio'].astype('int64')
prices_25['mes'] = prices_25['mes'].astype('int64')

### Canonical naming of `no_movimientos` and `exentos`.

In [9]:
for year, df in prices_dict.items():
    if year != "2025":
        print(year)
        print(f"no_novimientos values: {df['no_novimientos'].unique()}")
        print(f"exentos values: {df['exentos'].unique()}\n" + "==="*12)
    else:
        print(year)
        print(f"no_movimientos values: {df['no_movimientos'].unique()}")
        print(f"excentos values: {df['excentos'].unique()}\n" + "==="*12)

2022
no_novimientos values: ['NO' 'SI']
exentos values: ['f' 't' nan]
====================================
2023
no_novimientos values: ['NO' 'SI']
exentos values: ['f' nan 't']
====================================
2024
no_novimientos values: ['NO' 'SI']
exentos values: ['f' nan 't']
====================================
2025
no_movimientos values: ['NO' 'SI']
excentos values: ['f' nan 't']
====================================

We can confirm that these columns correspond to the same information.

Therefore, we can rename this fields to an only canonical name.

#### Column renaming
* Prices 22-24: `no_novimientos` -> `no_movimientos`
* Prices 25: `excentos` -> `exentos`

In [10]:
for year, df in prices_dict.items():
    if year != "2025":
        df.rename(columns={"no_novimientos": "no_movimientos"}, inplace=True)
    else:
        df.rename(columns={"excentos": "exentos"}, inplace=True)

### Duplicated rows

#### Full row

In [11]:
for year, df in prices_dict.items():
    print(year)
    print(f"Duplicated count: {df.duplicated().sum()}\n" + "==="*12)
duplicates = sum([df.duplicated().sum() for df in prices_dict.values()])
print(f"Total full row duplicates: {duplicates}")

2022
Duplicated count: 3
====================================
2023
Duplicated count: 5
====================================
2024
Duplicated count: 6
====================================
2025
Duplicated count: 14
====================================
Total full row duplicates: 28

#### Candidate key

In [12]:
print("Candidate key exploration")

eess_key = ['nro_inscripcion']

eess_attr = ['bandera', 'operador', 'tipo_negocio', 'provincia' , 'localidad', 'direccion']

num_eess_keys = sum([len(df[eess_key].drop_duplicates()) for df in prices_dict.values()])

print(f"\nNumber of keys ({eess_key}) \nwith more than one unique value of:")
print("==="*10)
for attr in eess_attr:
    n = 0
    for year, df in prices_dict.items():
        count = df.groupby(eess_key)[attr].nunique()
        n += len(count[count > 1])
    print(f"{attr:15}: {n}")
    print("==="*10)

print(f"Unique keys: {num_eess_keys}")

Candidate key exploration

Number of keys (['nro_inscripcion'])
with more than one unique value of:
==============================
bandera        : 1236
==============================
operador       : 0
==============================
tipo_negocio   : 0
==============================
provincia      : 0
==============================
localidad      : 0
==============================
direccion      : 0
==============================
Unique keys: 22144

In [13]:
period_key = ['anio', 'mes', 'nro_inscripcion']

multi_bandera = 0
for df in prices_dict.values():
    count = df.groupby(period_key)['bandera'].nunique()
    multi_bandera += len(count[count > 1])
num_keys = sum([len(df[period_key].drop_duplicates()) for df in prices_dict.values()])

print(f"Number of keys ({period_key}) \nwith more than unique value of 'bandera': {multi_bandera}")
print(f"Unique keys: {num_keys}")

Number of keys (['anio', 'mes', 'nro_inscripcion'])
with more than unique value of 'bandera': 6
Unique keys: 299431

In [14]:
instance_attr = ['canal_de_comercializacion', 'producto', 'exentos']

print("Possible instance attributes inspection")
print(f"\nPercentage of keys ({period_key}) \nwith more than one unique value of:")
print("==="*13)
for attr in instance_attr:
    n = 0
    for df in prices_dict.values():
        count = df.groupby(period_key)[attr].nunique()
        n += len(count[count > 1])
    print(f"{attr:28}: {100 * n / num_keys:.2f}%")
    print("==="*13)
print(f"Unique keys (denominator): {num_keys}")

Possible instance attributes inspection

Percentage of keys (['anio', 'mes', 'nro_inscripcion'])
with more than one unique value of:
=======================================
canal_de_comercializacion   : 11.97%
=======================================
producto                    : 83.85%
=======================================
exentos                     : 2.74%
=======================================
Unique keys (denominator): 299431

In [15]:
cand_key = ['anio', 'mes', 'nro_inscripcion', 'producto', 'canal_de_comercializacion', 'exentos']

print("Number of duplicates by incremental composite key.")
print(f"Key: {cand_key[:2]}\n" + "==="*15)
for i in range(len(cand_key)):
    if i < 2: continue
    n = 0
    for df in prices_dict.values():
        n += df.duplicated(subset=cand_key[:i+1]).sum()
    print(f"+ {cand_key[2:i+1]}")
    print(f"Duplicates: {n}\n" + "==="*15)
print(f"Full row duplicates: {duplicates}")

Number of duplicates by incremental composite key.
Key: ['anio', 'mes']
=============================================
+ ['nro_inscripcion']
Duplicates: 909819
=============================================
+ ['nro_inscripcion', 'producto']
Duplicates: 128941
=============================================
+ ['nro_inscripcion', 'producto', 'canal_de_comercializacion']
Duplicates: 579
=============================================
+ ['nro_inscripcion', 'producto', 'canal_de_comercializacion', 'exentos']
Duplicates: 29
=============================================
Full row duplicates: 28

### December 2024 inspection

In [16]:
selected_columns = [
    'anio',
    'mes',
    'cuit',
    'bandera',
    'operador',
    'nro_inscripcion',
    'provincia',
    'localidad',
    'direccion',
    'tipo_negocio',
    'canal_de_comercializacion',
    'producto',
    'volumen',
    'precio_sin_impuestos',
    'precio_con_impuestos',
    'precio_surtidor',
    'exentos',
    'fecha_de_baja',
    'no_movimientos'
]
comparison_columns = [col for col in selected_columns if col not in ('fecha_de_baja', '_merge')]

In [17]:
prices_dic24_1 = prices_24[(prices_24['anio']==2024) & (prices_24['mes']==12)][selected_columns]
prices_dic24_2 = prices_25[(prices_25['anio']==2024) & (prices_25['mes']==12)][selected_columns]
print(f"Number of rows\nPrices-24: {prices_dic24_1.shape[0]} \nPrices-25: {prices_dic24_2.shape[0]} \n" + "==="*15)

intersection = pd.merge(prices_dic24_1, prices_dic24_2, how="inner")
print(f"Number of exact duplicates between dataframes: {intersection.shape[0]}\n" + "==="*15)

intersected_keys = pd.merge(prices_dic24_1[cand_key], prices_dic24_2[cand_key], how="inner")
print(f"Number of duplicated keys between dataframes: {intersected_keys.shape[0]}\n" + "==="*15)

intersection_no_baja = pd.merge(prices_dic24_1[comparison_columns], prices_dic24_2[comparison_columns], how="inner")
print(f"Number of matching rows excluding fecha_de_baja and _merge: {intersection_no_baja.shape[0]}\n" + "==="*15)

Number of rows
Prices-24: 20700
Prices-25: 21601
=============================================
Number of exact duplicates between dataframes: 19139
=============================================
Number of duplicated keys between dataframes: 20686
=============================================
Number of matching rows excluding fecha_de_baja and _merge: 19316
=============================================

In [18]:
union = pd.merge(prices_dic24_1, prices_dic24_2, how="outer", indicator=True)
union_duplicated_key = union[union.duplicated(subset=cand_key, keep=False)]

In [19]:
union_dk_no_mov = union_duplicated_key[['_merge', 'no_movimientos']].value_counts()
print("Records with duplicated key between prices-24 and prices-25, with or without movements")
print(f"Prices-24: \n{union_dk_no_mov.loc['left_only']}\n" + "==="*10)
print(f"Prices-25: \n{union_dk_no_mov.loc['right_only']}\n")

Records with duplicated key between prices-24 and prices-25, with or without movements
Prices-24:
no_movimientos
NO    1535
SI      12
Name: count, dtype: int64
==============================
Prices-25:
no_movimientos
NO    1535
SI      12
Name: count, dtype: int64

### Record provenance traceability

In [20]:
union['provenance'] = union['_merge'].map(
    {
    "left_only": "prices_2024", 
    "right_only": "prices_2025", 
    "both": "both_2024_2025"
    }
)

In [21]:
for year, df in prices_dict.items():
    df['provenance'] = f"prices_{year}"

### Data concatenation

In [22]:
final_columns = selected_columns + ['provenance']

In [23]:
final_dataframes = [
    prices_22[final_columns],
    prices_23[final_columns],
    prices_24[prices_24['mes']!=12][final_columns],
    union[final_columns],
    prices_25[prices_25['periodo']!='2024/12'][final_columns],
]

In [24]:
prices = pd.DataFrame(pd.concat(final_dataframes))
n, m = prices.shape
print(f"Resulting dataframe shape: {n} x {m}\n" + "==="*15)
print(f"Number of duplicated full rows: {prices.duplicated().sum()}\n" + "==="*15)
print(f"Number of rows with duplicated keys: {prices.duplicated(subset=cand_key, keep=False).sum()}\n" + "==="*15)

Resulting dataframe shape: 1190111 x 20
=============================================
Number of duplicated full rows: 28
=============================================
Number of rows with duplicated keys: 3151
=============================================

#### Exclusion: 2026 records

In [25]:
print(f"2026 records: {len(prices[prices['anio']==2026])}")

prices = prices[prices['anio']!=2026]
print(f"Resulting rows: {prices.shape[0]}")

2026 records: 148321
Resulting rows: 1041790

### Flag: duplicated candidate key

In [26]:
prices['duplicated_key'] = prices.duplicated(subset=cand_key, keep=False)
print(f"Resulting rows with duplicated key: {len(prices[prices['duplicated_key']])}")

Resulting rows with duplicated key: 3141

### Deduplication: full rows

In [27]:
prices = prices.drop_duplicates()
print(f"Resulting rows: {prices.shape[0]}. Duplicated: {prices.duplicated().sum()}")

Resulting rows: 1041767. Duplicated: 0

### Numeric fields: descriptive statistics

In [28]:
prices.describe(percentiles=[0.5])

,anio,mes,nro_inscripcion,volumen,precio_sin_impuestos,precio_con_impuestos,precio_surtidor
count,1.041767e+06,1.041767e+06,1.041767e+06,1.041767e+06,1.041767e+06,1.041767e+06,1.041767e+06
mean,2.023499e+03,6.501519e+00,5.693367e+03,9.467414e+03,5.379281e+02,7.261687e+02,6.283246e+02
std,1.119603e+00,3.455079e+00,3.418284e+03,4.392081e+05,4.176822e+02,5.730653e+02,5.951478e+02
min,2.022000e+03,1.000000e+00,1.010000e+02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2.023000e+03,6.000000e+00,6.003000e+03,5.800300e+01,3.966120e+02,4.990000e+02,3.152000e+02
max,2.025000e+03,1.200000e+01,1.152500e+04,3.550410e+08,4.910000e+03,4.999000e+03,5.000000e+03

There's no negativeness in the numeric fields, but there are zeros in prices and volume.

### Column missingness

In [29]:
print("Column missing values")
for col in prices.columns:
    print(f"{col:28}: {prices[col].isna().sum()}")

Column missing values
anio                        : 0
mes                         : 0
cuit                        : 0
bandera                     : 0
operador                    : 0
nro_inscripcion             : 0
provincia                   : 0
localidad                   : 0
direccion                   : 14
tipo_negocio                : 0
canal_de_comercializacion   : 0
producto                    : 0
volumen                     : 0
precio_sin_impuestos        : 0
precio_con_impuestos        : 0
precio_surtidor             : 0
exentos                     : 9489
fecha_de_baja               : 1004729
no_movimientos              : 0
provenance                  : 0
duplicated_key              : 0

### Categorical value profiling

In [30]:
categorical_columns = prices.select_dtypes(include=['object', 'category']).columns
print('Categorical field cardinality:')
for col in categorical_columns:
    print(f"{col:28}: {prices[col].nunique(dropna=False)}")

Categorical field cardinality:
cuit                        : 3819
bandera                     : 23
operador                    : 4358
provincia                   : 24
localidad                   : 1177
direccion                   : 5976
tipo_negocio                : 12
canal_de_comercializacion   : 8
producto                    : 9
exentos                     : 3
fecha_de_baja               : 334
no_movimientos              : 2
provenance                  : 5

In [31]:
for col in categorical_columns:
    n = prices[col].nunique(dropna=False)
    if n < 10:
        print(f"Column {col} has {n} distinct values. Category distribution:")
        display(prices[col].value_counts(dropna=False).reset_index())
    else:
        continue

Column canal_de_comercializacion has 8 distinct values. Category distribution:

                        canal_de_comercializacion   count
0                                      Al público  882439
1                                            Agro   52330
2                            Transporte de cargas   40877
3                                  Otros sectores   30323
4          Reventa a otras estaciones de servicio   14208
5                 Transporte público de pasajeros   11290
6                                             N/D    9489
7  Vehículos con placa identificatoria extranjera     811

Column producto has 9 distinct values. Category distribution:

                           producto   count
0                   Gas Oil Grado 2  261733
1                   Gas Oil Grado 3  237048
2   Nafta (súper) entre 92 y 95 Ron  221255
3  Nafta (premium) de más de 95 Ron  206207
4                               GNC   95471
5                               N/D    9489
6                          Kerosene    8151
7        Nafta (común) hasta 92 Ron    2246
8                              GLPA     167

Column exentos has 3 distinct values. Category distribution:

  exentos    count
0       f  1004528
1       t    27750
2     NaN     9489

Column no_movimientos has 2 distinct values. Category distribution:

  no_movimientos    count
0             NO  1032278
1             SI     9489

Column provenance has 5 distinct values. Category distribution:

       provenance   count
0     prices_2025  263704
1     prices_2022  261470
2     prices_2023  259801
3     prices_2024  237653
4  both_2024_2025   19139

Concerning missing values ("NaN", "N/D"), there might be some relation between the different fields and no_movimientos = "SI". This relation is inspected later below.

#### Text normalization: cardinality comparison
In order to prove if there is a reduction (or not) of the cardinality after text normalization (remove accents, normalize casing, strip spaces on the edges and delete multiple spaces between words)

In [32]:
import unicodedata
import re

def remove_accents(text: str) -> str:
    normalized = unicodedata.normalize("NFKD", text)
    return "".join(
        char for char in normalized if not unicodedata.combining(char)
    )

def normalize_text(text: str) -> str:
    """Normalize a non-null text value without changing its semantics."""
    if pd.isna(text):
        return text
    text = str(text).strip().lower()
    text = remove_accents(text)
    text = re.sub(r"\s+", " ", text)
    return text

In [33]:
prices_norm_txt = prices.copy()
for col in categorical_columns:
    prices_norm_txt[col] = prices[col].apply(normalize_text)

In [34]:
print("Text normalization cardinality test:\n" + " "*15 + "Before | After")
for col in prices.select_dtypes(include=['object']).columns:
    if col != 'fecha_de_baja' and prices[col].nunique() >= 10:
        before = prices[col].nunique()
        after = prices_norm_txt[col].nunique()
        print(f"{col:15}{before:7}|{after:6} diff={before-after}")

Text normalization cardinality test:
               Before | After
cuit              3819|  3819 diff=0
bandera             23|    23 diff=0
operador          4358|  4336 diff=22
provincia           24|    24 diff=0
localidad         1177|  1177 diff=0
direccion         5975|  5926 diff=49
tipo_negocio        12|    12 diff=0

#### Missing text values variants

In [35]:
null_text_variants = ["", "nan", "n/d"]

print(" "*27 + "  Nulls  | Null variants")
for col in categorical_columns:
    null_variants = prices_norm_txt[col].isin(null_text_variants).sum()
    nulls = prices_norm_txt[col].isna().sum()
    print(f"{col:26}: {nulls:7} | {null_variants}")

                             Nulls  | Null variants
cuit                      :       0 | 0
bandera                   :       0 | 0
operador                  :       0 | 0
provincia                 :       0 | 0
localidad                 :       0 | 0
direccion                 :      14 | 0
tipo_negocio              :       0 | 1287
canal_de_comercializacion :       0 | 9489
producto                  :       0 | 9489
exentos                   :    9489 | 0
fecha_de_baja             : 1004729 | 0
no_movimientos            :       0 | 0
provenance                :       0 | 0

### Duplicated with inconsistent `no_movimientos` values

In [36]:
duplicated = prices[prices['duplicated_key']]
inconsistent_no_mov = duplicated.groupby(cand_key)['no_movimientos'].nunique()
inconsistent_no_mov = inconsistent_no_mov[inconsistent_no_mov > 1]

print("Number of keys with inconsistent 'no_movimientos':")
print(len(inconsistent_no_mov))

Number of keys with inconsistent 'no_movimientos':
0

### `no_movimientos` = "SI" inspection

In [37]:
pd.set_option("display.max_columns", None)

In [38]:
no_mov = prices[prices['no_movimientos'] == "SI"].copy()
no_mov.sample(3)

,anio,mes,cuit,bandera,operador,nro_inscripcion,provincia,localidad,direccion,tipo_negocio,canal_de_comercializacion,producto,volumen,precio_sin_impuestos,precio_con_impuestos,precio_surtidor,exentos,fecha_de_baja,no_movimientos,provenance,duplicated_key
69827,2025,3,30-66604945-0,BLANCA,COMPAÑIA PETROLERA COPSA SA,368,BUENOS AIRES,PEHUAJO,H. YRIGOYEN 707,Bocas de expendio (venta por menor) Combustibl...,N/D,N/D,0.0,0.0,0.0,0.0,NaN,16/2026/04,SI,prices_2025,False
212186,2025,9,30-70863366-2,BLANCA,PETROEX S.A.,1396,CHUBUT,TRELEW,COLOMBIA 440 Y PELLEGRINI,Bocas de expendio (venta por menor) Combustibl...,N/D,N/D,0.0,0.0,0.0,0.0,NaN,NaN,SI,prices_2025,False
187406,2023,9,30-67162857-4,BLANCA,MORAN MANERA Y OTROS,6542,MENDOZA,GRAL. ALVEAR,RUTA 143 KM.582,Bocas de expendio (venta por menor) Sólo GNC,N/D,N/D,0.0,0.0,0.0,0.0,NaN,NaN,SI,prices_2023,False

The behaviour of these rows appears to be: all prices fields plus volume field are zero; market channel, tax exemption and product fields are missing.

In [39]:
price_cols = ['precio_con_impuestos', 'precio_sin_impuestos', 'precio_surtidor']
cat_cols = ['canal_de_comercializacion', 'producto']

no_mov_with_price = no_mov[(no_mov[price_cols] == 0).all(axis=1)]
no_mov_with_cats = no_mov[(no_mov[cat_cols] == "N/D").all(axis=1)]

print("Rows with 'no_movimientos' = SI and:")
print(f"-all price columns equal zero: {len(no_mov_with_price)}")
print(f"-volume column equal zero: {len(no_mov[no_mov['volumen'] == 0])}")
print(f"-null exentos value: {len(no_mov[no_mov['exentos'].isna()])}")
print(f"-every instance category is null: {len(no_mov_with_cats)}")
print(f"\nTotal rows: {len(no_mov)}")

Rows with 'no_movimientos' = SI and:
-all price columns equal zero: 9489
-volume column equal zero: 9489
-null exentos value: 9489
-every instance category is null: 9489

Total rows: 9489

100% of the rows flagged as no movements have consistently the same behaviour.

### `no_movimientos` = "NO" inspection
To assess wether there is the behaviour previously seen or not.

In [42]:
with_move = prices[prices['no_movimientos']=="NO"]

no_mov_wo_price = with_move[(with_move[price_cols] == 0).any(axis=1)]
no_mov_wo_cats = with_move[(with_move[cat_cols] == "N/D").any(axis=1)]

print("Rows with 'no_movimientos' = NO and:")
print(f"-any price column is zero: {len(no_mov_wo_price)}")
print(f"-volume column is zero: {len(with_move[with_move['volumen'] == 0])}")
print(f"-null exentos value: {len(with_move[with_move['exentos'].isna()])}")
print(f"-any instance category is null: {len(no_mov_wo_cats)}")
print(f"\nTotal rows: {len(with_move)}")

Rows with 'no_movimientos' = NO and:
-any price column is zero: 149410
-volume column is zero: 0
-null exentos value: 0
-any instance category is null: 0

Total rows: 1032278

### Rows with price columns equal zero

In [43]:
(with_move[price_cols] == 0).sum()

precio_con_impuestos         0
precio_sin_impuestos         0
precio_surtidor         149410
dtype: int64

For the rest of this section, "no price rows" will be used to reference those rows with `precio_surtidor == 0`

In [66]:
print("Essential fields insection")
for col in cand_key:
    display(with_move[with_move['precio_surtidor']==0][col].value_counts().reset_index().head(10))
    print("==="*15)

Essential fields insection

   anio  count
0  2025  38784
1  2022  37746
2  2023  37051
3  2024  35829

=============================================

   mes  count
0    3  12584
1    6  12551
2    5  12530
3   11  12490
4   12  12489
5    8  12480
6    7  12462
7    2  12439
8    1  12385
9   10  12370

=============================================

   nro_inscripcion  count
0             7073    985
1              641    961
2              427    953
3             2417    929
4              642    879
5             8398    856
6            10421    839
7              296    828
8             9846    827
9             5266    821

=============================================

                           producto  count
0                   Gas Oil Grado 2  68583
1                   Gas Oil Grado 3  40325
2   Nafta (súper) entre 92 y 95 Ron  20089
3  Nafta (premium) de más de 95 Ron  15587
4                               GNC   3364
5                          Kerosene   1342
6        Nafta (común) hasta 92 Ron    119
7                              GLPA      1

=============================================

                        canal_de_comercializacion  count
0                                            Agro  52330
1                            Transporte de cargas  40877
2                                  Otros sectores  30323
3          Reventa a otras estaciones de servicio  14208
4                 Transporte público de pasajeros  11290
5  Vehículos con placa identificatoria extranjera    382

=============================================

  exentos   count
0       f  145369
1       t    4041

=============================================

In [48]:
with_move[with_move['precio_surtidor']==0]['canal_de_comercializacion'].value_counts().reset_index()

                        canal_de_comercializacion  count
0                                            Agro  52330
1                            Transporte de cargas  40877
2                                  Otros sectores  30323
3          Reventa a otras estaciones de servicio  14208
4                 Transporte público de pasajeros  11290
5  Vehículos con placa identificatoria extranjera    382

In [72]:
not_public_rows = with_move[with_move['canal_de_comercializacion'] != "Al público"]
wo_price_rows = with_move[with_move['precio_surtidor'] == 0]

not_public_wo_price = wo_price_rows.merge(not_public_rows, how="outer", indicator=True)
is_subset = not_public_wo_price["_merge"].isin(["right_only", "both"]).all()

print(f"Missing price rows are a subset of the complement of public sales? {is_subset}")

Missing price rows are a subset of the complement of public sales? True

### a

In [78]:
right_only = not_public_wo_price[not_public_wo_price['_merge']=="right_only"]

right_only['canal_de_comercializacion'].value_counts().reset_index()

                        canal_de_comercializacion  count
0  Vehículos con placa identificatoria extranjera    429

In [87]:
right_only[price_cols].sample(5)

        precio_con_impuestos  precio_sin_impuestos  precio_surtidor
35460                300.000               236.656            300.0
20336                144.900               103.700            144.9
120953              1298.870               946.070           1303.0
6776                 175.569               133.770            190.0
53823                370.539               302.197            390.0

In [81]:
is_eq_prices = (right_only['precio_con_impuestos'] == right_only['precio_surtidor']).all()

print(f"Every 'precio_surtidor' equals to 'precio_con_impuestos'? {is_eq_prices}")

Every 'precio_surtidor' equals to 'precio_con_impuestos'? False